#!/usr/bin/env julia
# scripts/assemble_manuscript.jl
using CSV
using DataFrames
using Dates
using JSON3
using LinearAlgebra
using Statistics

const DEFAULT_DATASET = "CASES99"
const DEFAULT_GENERATED_DATE_HUMAN = "July 13, 2026"

function first_existing_dir(paths::Vector{String})
    for path in paths
        if isdir(path)
            entries = filter(name -> name != ".gitkeep", readdir(path))
            if !isempty(entries)
                return path
            end
        end
    end
    return first(paths)
end

function parse_args(args::Vector{String})
    dataset = DEFAULT_DATASET
    generated_date_human = DEFAULT_GENERATED_DATE_HUMAN

    i = 1
    while i <= length(args)
        arg = args[i]
        if arg == "--dataset" && i < length(args)
            dataset = args[i+1]
            i += 2
        elseif arg == "--date" && i < length(args)
            generated_date_human = args[i+1]
            i += 2
        else
            error("Unknown or incomplete argument: $(arg)")
        end
    end
    return uppercase(String(strip(dataset))), String(strip(generated_date_human))
end

function read_text(path::String; fallback::String="")
    return isfile(path) ? read(path, String) : fallback
end

function render_template(template::String, context::Dict{String,String})
    rendered = template
    for (k, v) in context
        rendered = replace(rendered, "{{{$(k)}}}" => v)
        rendered = replace(rendered, "{{$(k)}}" => v)
    end
    return rendered
end

function build_optional_tex_template(path::String, context::Dict{String,String}; fallback::String="")
    if !isfile(path)
        return fallback
    end
    rendered = render_template(read_text(path), context)
    return "% --- Begin Section: $(path) ---\n" * rendered * "\n% --- End Section: $(path) ---"
end

function build_tex_template_sections(section_dir::String, context::Dict{String,String})
    if !isdir(section_dir)
        return "% No template sections directory found."
    end

    all_tex_templates = sort(filter(name -> endswith(name, ".tex.mustache"), readdir(section_dir)))
    if isempty(all_tex_templates)
        return "% No TeX section templates found."
    end

    wrapper_name = "section_theory.tex.mustache"
    front_matter_templates = Set(["abstract.tex.mustache"])
    content_templates = filter(name -> (name != wrapper_name) && !(name in front_matter_templates), all_tex_templates)

    preferred_order = [
        "governing_system.tex.mustache",
        "governing_equations.tex.mustache",
        "critical_manifold_geometry.tex.mustache",
        "regularization.tex.mustache",
        "mathematical_formulation_regularization_thermal_shift.tex.mustache",
        "comparative_metrics.tex.mustache",
        "numerical_implementation_solver_strategy.tex.mustache",
        "numerical_verification_physical_interpretation.tex.mustache",
        "closures.tex.mustache",
        "parameters_geometry.tex.mustache",
    ]

    ordered_templates = String[]
    for name in preferred_order
        if name in content_templates
            push!(ordered_templates, name)
        end
    end

    for name in content_templates
        if !(name in ordered_templates)
            push!(ordered_templates, name)
        end
    end

    content_blocks = String[]
    for file in ordered_templates
        template_path = joinpath(section_dir, file)
        template_text = read_text(template_path)
        rendered = render_template(template_text, context)

        # Inject explicit source traceability comments
        commented_block = "% --- Begin Section: $(template_path) ---\n" * rendered * "\n% --- End Section: $(template_path) ---"
        push!(content_blocks, commented_block)
    end

    content_joined = join(content_blocks, "\n\n")
    if wrapper_name in all_tex_templates
        wrapper_path = joinpath(section_dir, wrapper_name)
        wrapper_text = read_text(wrapper_path)
        wrapper_context = copy(context)
        wrapper_context["content"] = content_joined
        rendered_wrapper = render_template(wrapper_text, wrapper_context)
        return "% --- Begin Wrapper: $(wrapper_path) ---\n" * rendered_wrapper * "\n% --- End Wrapper: $(wrapper_path) ---"
    end

    return content_joined
end

function build_tex_figure_includes(fig_dir::String; tex_output_dir::String=joinpath("reports", "generated"))
    if !isdir(fig_dir)
        return "% No generated figures directory found."
    end

    FIGURE_METADATA = Dict(
        "figure_bifurcation_fold_envelope" => (
            title="Comparative benchmark: Bifurcation envelope under a classical interior fold scenario (shown for structural comparison only; not generated by the present model). This illustrates the scenario where the active turbulent branch loses normal hyperbolicity at an interior saddle-node locus.",
            label="fig:fold_envelope",
        ),
        "figure_bifurcation_fold_map" => (
            title="Comparative benchmark: Topological phase-space map of an interior fold regime (shown for comparison only). Vector fields highlight the catastrophic jump dynamics occurring at an interior fold point, contrasting with the boundary-crossing mechanics of the present system.",
            label="fig:fold_map",
        ),
        "figure_bifurcation_transcritical_envelope" => (
            title="Transcritical bifurcation envelope corresponding to the transversal boundary crossing regime (\$e=0\$). The diagram illustrates the smooth transition tracking the physical admissibility threshold \$\\Delta = \\delta / l_0\$.",
            label="fig:transcritical_envelope",
        ),
        "figure_bifurcation_transcritical_map" => (
            title="Trajectory flow field mapping the non-folding boundary crossing. The phase portraits confirm that the system transitions smoothly onto the regularized background laminar floor without undergoing an interior saddle-node collapse.",
            label="fig:transcritical_map",
        ),
        "4d_sbl_diagnostics" => (
            title="Complete 4D time-series trajectories and phase-space projections for the nocturnal stable boundary layer simulated under CASES99 conditions. The panels illustrate the rapid initial turbulent decay followed by the slow ageostrophic development of the nocturnal low-level jet.",
            label="fig:sbl_diagnostics",
        ),
        "diagnostic_regularization_comparison" => (
            title="Comparative analysis of the state-derived vertical eddy diffusivities (\$K_m, K_h\$) versus the \$C^\\infty\$ regularized hyperbolic embedded tracks (\$K_{m,\\star}, K_{h,\\star}\$) defined in Eq.~\\eqref{eq:embedded_diffusivities}. The comparison illustrates how the smooth embedding smooths out the sharp gradient kinks at the collapse threshold while ensuring a bounded closure Jacobian \$J_K\$.",
            label="fig:regularization_comparison",
        ),
    )

    function figure_caption_and_label(stem::String)
        if haskey(FIGURE_METADATA, stem)
            meta = FIGURE_METADATA[stem]
            return meta.title, meta.label
        end
        return prettify_figure_title(stem), ""
    end

    function make_figure_block(path::String, caption::String, label::String)
        rel_path = relpath(path, tex_output_dir)
        label_line = isempty(label) ? "" : "\n\\label{$(label)}"
        return "\\begin{figure}[ht!]\n\\centering\n\\includegraphics[width=0.95\\linewidth]{$(rel_path)}\n\\caption{$(caption)}$(label_line)\n\\end{figure}"
    end

    function prettify_figure_title(stem::String)
        parts = split(replace(stem, "-" => "_"), "_")
        normalized = String[]
        for part in parts
            lw = lowercase(part)
            if lw == "4d"
                push!(normalized, "4D")
            elseif lw == "sbl"
                push!(normalized, "SBL")
            elseif lw == "tke"
                push!(normalized, "TKE")
            elseif lw == "gspt"
                push!(normalized, "GSPT")
            elseif lw == "nwp"
                push!(normalized, "NWP")
            else
                push!(normalized, uppercasefirst(lw))
            end
        end
        return join(normalized, " ")
    end

    tex_files = sort(filter(name -> startswith(name, "figure_bifurcation_") && endswith(name, ".tex"), readdir(fig_dir)))
    handled_stems = Set{String}()

    blocks = String[]
    for file in tex_files
        stem = replace(file, ".tex" => "")
        push!(handled_stems, stem)
        title, label = figure_caption_and_label(stem)
        pdf_path = joinpath(fig_dir, "$(stem).pdf")
        push!(blocks, make_figure_block(pdf_path, title, label))
    end

    image_files = sort(filter(name -> (
            (endswith(name, ".png") || endswith(name, ".jpg") || endswith(name, ".jpeg") || endswith(name, ".pdf"))
        ), readdir(fig_dir)))

    for file in image_files
        stem = replace(file, r"\.[^.]+$" => "")
        if stem in handled_stems
            continue
        end
        title, label = figure_caption_and_label(stem)
        img_path = joinpath(fig_dir, file)
        push!(blocks, make_figure_block(img_path, title, label))
    end

    if isempty(blocks)
        return "% No generated figure assets found."
    end

    return join(blocks, "\n\n")
end

function build_md_figure_includes(fig_dir::String)
    if !isdir(fig_dir)
        return "No generated figures directory found."
    end

    md_files = sort(filter(name -> startswith(name, "figure_bifurcation_") && endswith(name, ".md"), readdir(fig_dir)))

    lines = String[]
    for file in md_files
        push!(lines, "- reports/generated/figures/$(file)")
    end

    image_files = sort(filter(name -> (
            endswith(name, ".png") || endswith(name, ".jpg") || endswith(name, ".jpeg") || endswith(name, ".pdf")
        ), readdir(fig_dir)))

    for file in image_files
        push!(lines, "- reports/generated/figures/$(file)")
    end

    if isempty(lines)
        return "No generated figure assets found."
    end

    return join(lines, "\n")
end

function format_metric(value)
    return isnan(value) ? "\\mathrm{n/a}" : string(round(value; digits=4))
end

function latex_escape(s::AbstractString)
    out = s
    out = replace(out, "\\" => "\\textbackslash{}")
    out = replace(out, "{" => "\\{")
    out = replace(out, "}" => "\\}")
    out = replace(out, "_" => "\\_")
    out = replace(out, "%" => "\\%")
    out = replace(out, "#" => "\\#")
    out = replace(out, "&" => "\\&")
    out = replace(out, string('$') => "\\\$")
    return out
end

function getnested(obj, keys::Vector{String}, default="n/a")
    cur = obj
    for k in keys
        if cur isa AbstractDict
            if haskey(cur, k)
                cur = cur[k]
            elseif haskey(cur, Symbol(k))
                cur = cur[Symbol(k)]
            else
                return default
            end
        else
            try
                cur = getproperty(cur, Symbol(k))
            catch
                return default
            end
        end
    end
    return cur
end

function format_int_commas(x)
    x isa Integer || return string(x)
    s = reverse(string(abs(x)))
    chunks = [reverse(s[i:min(i+2, end)]) for i in 1:3:length(s)]
    out = join(reverse(chunks), ",")
    return x < 0 ? "-$(out)" : out
end

function format_float_digits(x, digits::Int; fallback="n/a")
    x isa Number || return fallback
    return string(round(Float64(x); digits=digits))
end

function format_percent(x; digits::Int=1, fallback="n/a")
    x isa Number || return fallback
    pct = round(100 * Float64(x); digits=digits)
    if digits == 0
        return string(Int(round(pct)))
    end
    return string(pct)
end

function compact_solver_name(s::AbstractString)
    m = match(r"Rodas[0-9A-Za-z]+", s)
    m === nothing && return s
    return m.match
end

function find_scm_summary_path()
    candidates = [
        joinpath("results", "scm_verify", "summary.json"),
        joinpath("results", "idealized_sbl", "summary.json"),
        joinpath("results", "idealized_sbl_smoke", "summary.json"),
    ]
    for path in candidates
        if isfile(path)
            return path
        end
    end

    discovered = String[]
    if isdir("results")
        for entry in readdir("results")
            summary_path = joinpath("results", entry, "summary.json")
            plots_dir = joinpath("results", entry, "plots")
            if isfile(summary_path) && isdir(plots_dir)
                push!(discovered, summary_path)
            end
        end
    end
    if !isempty(discovered)
        sort!(discovered; by=path -> stat(path).mtime, rev=true)
        return first(discovered)
    end

    return ""
end

function read_scm_summary_context()
    path = find_scm_summary_path()
    if isempty(path)
        return Dict{String,String}(
            "scm_case_name" => "n/a",
            "scm_solver_name" => "n/a",
            "scm_rhs_evaluations" => "n/a",
            "scm_surface_energy_closure_error" => "n/a",
            "scm_km_min" => "n/a",
            "scm_km_max" => "n/a",
            "scm_fold_fraction_percent" => "n/a",
            "scm_phase_figure_block" => "% SCM phase portrait figure unavailable",
            "scm_all_figures_block" => "% SCM figures unavailable",
        )
    end

    raw = read(path, String)
    summary = JSON3.read(raw)

    solver_algorithm = string(getnested(summary, ["solver_summary", "algorithm"], "n/a"))
    rhs_evals = getnested(summary, ["solver_summary", "rhs_evaluations"], "n/a")
    max_surface_error = getnested(summary, ["verification", "max_surface_energy_closure_error"], "n/a")
    km_min = getnested(summary, ["verification", "min_diffusivity"], "n/a")
    km_max = getnested(summary, ["verification", "max_diffusivity"], "n/a")
    fold_fraction = getnested(summary, ["verification", "fold_near_fraction"], "n/a")
    case_name = string(getnested(summary, ["case"], "n/a"))
    outdir = string(getnested(summary, ["outdir"], dirname(path)))

    SCM_FIG_META = Dict(
        "fig01" => (
            caption="Time-series evolution of surface skin temperature \\(T_s\\), surface sensible heat flux \\(H\\), and friction velocity \\(u_*\\) over the course of the simulation.",
            label="fig:scm_time_series",
        ),
        "fig02" => (
            caption="Time-height contour map representing horizontal wind speed \\(U\\), demonstrating the gradual aloft development and consolidation of the nocturnal low-level jet (LLJ).",
            label="fig:scm_wind_contour",
        ),
        "fig03" => (
            caption="Time-height contour of potential temperature \\(\\theta\\), demonstrating surface-driven nocturnal radiative cooling and progressive boundary-layer inversion growth.",
            label="fig:scm_theta_contour",
        ),
        "fig04" => (
            caption="Representative vertical profiles of horizontal wind speed \\(U\\), potential temperature \\(\\theta\\), and momentum eddy diffusivity \\(K_m\\) at diagnostic times.",
            label="fig:scm_profiles",
        ),
        "fig05" => (
            caption="Surface energy budget (SEB) components illustrating the dynamic balance of net radiation \\(R_n\\), sensible heat flux \\(H\\), soil heat flux \\(G\\), and surface-storage thermal layers.",
            label="fig:scm_surface_energy",
        ),
        "fig06" => (
            caption="Regularized slow-manifold phase portrait mapping the net TKE production-buoyancy balance \\(\\Delta\\) against the regularized coordinate \\(e_\\xi^*\\) across characteristic height bands (surface, mid-BL jet core, and upper boundary layer). The vertical reference line shows the analytical critical transition condition \\(\\Delta = \\delta / \\ell_0\\).",
            label="fig:scm_phase_delta_exi",
        ),
        "fig07" => (
            caption="Momentum and heat eddy diffusivities (\\(K_m, K_h\\)) displayed against the local gradient Richardson stability metric (\\(Ri\\)).",
            label="fig:scm_diffusivity",
        ),
        "fig08" => (
            caption="Temporal evolution of the surface fold-proximity metric, showing the proximity of the surface state relative to the regularized manifold transition boundary.",
            label="fig:scm_fold_proximity",
        ),
    )

    phase_fig_path = joinpath(outdir, "plots", "fig06_phase_delta_exi.png")
    phase_fig_block = "% SCM phase portrait figure unavailable"

    scm_plots_dir = joinpath(outdir, "plots")
    all_scm_blocks = String[]
    if isdir(scm_plots_dir)
        scm_image_files = sort(filter(name -> (
                endswith(name, ".png") || endswith(name, ".jpg") || endswith(name, ".jpeg") || endswith(name, ".pdf")
            ), readdir(scm_plots_dir)))

        for file in scm_image_files
            stem = replace(file, r"\.[^.]+$" => "")
            prefix_match = match(r"fig\d+", stem)
            prefix = prefix_match === nothing ? stem : prefix_match.match

            caption, label = if haskey(SCM_FIG_META, prefix)
                SCM_FIG_META[prefix].caption, SCM_FIG_META[prefix].label
            else
                fallback_label = "fig:scm_" * lowercase(replace(stem, r"[^A-Za-z0-9]+" => "_"))
                prettify_figure_title(stem), fallback_label
            end

            img_path = joinpath(scm_plots_dir, file)
            rel_img_path = relpath(img_path, joinpath("reports", "generated"))
            fig_latex = "\\begin{figure}[ht!]\n\\centering\n\\includegraphics[width=0.95\\linewidth]{\\detokenize{$(rel_img_path)}}\n\\caption{$(caption)}\n\\label{$(label)}\n\\end{figure}"
            push!(all_scm_blocks, fig_latex)

            if prefix == "fig06"
                phase_fig_block = fig_latex
            end
        end
    end

    scm_all_figures_block = isempty(all_scm_blocks) ? "% SCM figures unavailable" : join(all_scm_blocks, "\n\n")

    return Dict{String,String}(
        "scm_case_name" => latex_escape(case_name),
        "scm_solver_name" => latex_escape(compact_solver_name(solver_algorithm)),
        "scm_rhs_evaluations" => format_int_commas(rhs_evals),
        "scm_surface_energy_closure_error" => format_float_digits(max_surface_error, 0),
        "scm_km_min" => format_float_digits(km_min, 3),
        "scm_km_max" => format_float_digits(km_max, 2),
        "scm_fold_fraction_percent" => format_percent(fold_fraction; digits=0),
        "scm_phase_figure_block" => phase_fig_block,
        "scm_all_figures_block" => scm_all_figures_block,
    )
end

function quadratic_fit_rmse(solution_csv::String)
    if !isfile(solution_csv)
        return NaN
    end

    df = CSV.read(solution_csv, DataFrame)
    if !all(name -> name in names(df), ["U", "V", "Ts"])
        return NaN
    end

    U = Vector{Float64}(df.U)
    V = Vector{Float64}(df.V)
    Ts = Vector{Float64}(df.Ts)
    X = hcat(ones(length(U)), U, V, U .^ 2, U .* V, V .^ 2)
    coef = X \ Ts
    residual = Ts - X * coef
    return sqrt(mean(residual .^ 2))
end

function latest_solution_csv(dataset::String)
    latest_path = joinpath("results", dataset, "latest", "solution.csv")
    if isfile(latest_path)
        return latest_path
    end

    run_root = joinpath("results", dataset)
    if isdir(run_root)
        run_dirs = sort(
            filter(name -> startswith(name, "run_") && isdir(joinpath(run_root, name)), readdir(run_root));
            rev=true,
        )
        for run_dir in run_dirs
            candidate = joinpath(run_root, run_dir, "solution.csv")
            if isfile(candidate)
                return candidate
            end
        end
    end

    if dataset == "CASES99"
        legacy_root = joinpath("results", "4d_sbl")
        if isdir(legacy_root)
            legacy_dirs = sort(
                filter(name -> startswith(name, "run_") && isdir(joinpath(legacy_root, name)), readdir(legacy_root));
                rev=true,
            )
            for run_dir in legacy_dirs
                candidate = joinpath(legacy_root, run_dir, "solution.csv")
                if isfile(candidate)
                    return candidate
                end
            end
        end
    end

    return latest_path
end

dataset, generated_date_human = parse_args(ARGS)

mkpath("reports/generated")

tex_out = "reports/generated/paper.tex"
md_out = "reports/generated/paper.md"

tex_template_path = "templates/paper.tex.mustache"
md_template_path = "templates/paper.md.mustache"

tex_template = read_text(tex_template_path; fallback="\\documentclass{article}\\begin{document}Template missing.\\end{document}")
md_template = read_text(md_template_path; fallback="# Template missing")

theory_md = read_text("reports/generated/theory/01_state_space.md"; fallback="Theory section not generated yet.")
archive_md = read_text("reports/generated/theory/02_archive_synthesis.md"; fallback="Archive synthesis not generated yet.")
diag_md = read_text("reports/generated/diagnostics/03_bifurcation_sweep.md"; fallback="Diagnostics section not generated yet.")

fig_dir = first_existing_dir(["reports/generated/figures", "figures"])
figure_tex_includes = build_tex_figure_includes(fig_dir; tex_output_dir=dirname(tex_out))
figure_md_includes = build_md_figure_includes(fig_dir)

timestamp = string(Dates.now())

section_context = Dict(
    "dataset" => dataset,
    "generated_timestamp" => timestamp,
    "generated_date_human" => generated_date_human,
    "cases99_rmse" => format_metric(quadratic_fit_rmse(latest_solution_csv("CASES99"))),
    "floss_rmse" => format_metric(quadratic_fit_rmse(latest_solution_csv("FLOSS"))),
    "sheba_rmse" => format_metric(quadratic_fit_rmse(latest_solution_csv("SHEBA"))),
)
merge!(section_context, read_scm_summary_context())
template_sections_tex = build_tex_template_sections("templates/sections", section_context)
abstract_tex = build_optional_tex_template(
    "templates/sections/abstract.tex.mustache",
    section_context;
    fallback="",
)

tex_context = Dict(
    "dataset" => dataset,
    "generated_timestamp" => timestamp,
    "generated_date_human" => generated_date_human,
    "abstract_tex" => abstract_tex,
    "template_sections_tex" => template_sections_tex,
    "figure_tex_includes" => figure_tex_includes,
)

md_context = Dict(
    "dataset" => dataset,
    "generated_timestamp" => timestamp,
    "theory_section" => theory_md,
    "archive_synthesis_section" => archive_md,
    "diagnostics_section" => diag_md,
    "figure_md_includes" => figure_md_includes,
)

rendered_tex = render_template(tex_template, tex_context)
rendered_md = render_template(md_template, md_context)

write(tex_out, rendered_tex)
write(md_out, rendered_md)

println("Generated manuscript files with section annotations:")
println(tex_out)
println(md_out)