#!/usr/bin/env julia
# scripts/generate_symbols.jl - Symbol Single Source of Truth (SSOT) Generator
# This script generates LaTeX and Markdown representations of the symbols defined in `spec/symbols.yaml`.

module SymbolSSOT

using YAML

export generate_symbols_assets

const REQUIRED_SYMBOL_KEYS = [
    "id",
    "symbol_tex",
    "symbol_md",
    "code_key",
    "units_tex",
    "units_md",
    "name",
    "description",
    "category",
]

function _read_yaml(path::String)
    isfile(path) || error("Missing symbols spec: $(path)")
    return YAML.load_file(path)
end

function _latex_escape(s::AbstractString)
    # Simultaneous single-pass replacement prevents re-escaping generated braces/slashes
    return replace(
        String(s),
        "\\" => "\\textbackslash{}",
        "{" => "\\{",
        "}" => "\\}",
        "_" => "\\_",
        "%" => "\\%",
        "#" => "\\#",
        "&" => "\\&",
        "~" => "\\textasciitilde{}"
    )
end

function _validate_spec(spec)
    haskey(spec, "schema_version") || error("symbols.yaml missing schema_version")
    haskey(spec, "categories") || error("symbols.yaml missing categories")
    haskey(spec, "symbols") || error("symbols.yaml missing symbols")

    categories = spec["categories"]
    symbols = spec["symbols"]
    categories isa AbstractVector || error("symbols categories must be a list")
    symbols isa AbstractVector || error("symbols symbols must be a list")

    cat_ids = String[]
    for c in categories
        c isa AbstractDict || error("Each category entry must be a mapping")
        haskey(c, "id") || error("Category entry missing id")
        haskey(c, "name") || error("Category $(c) missing name")
        push!(cat_ids, String(c["id"]))
    end

    length(unique(cat_ids)) == length(cat_ids) || error("Duplicate category ids in symbols.yaml")
    cat_set = Set(cat_ids)

    ids = String[]
    for s in symbols
        s isa AbstractDict || error("Each symbol entry must be a mapping")
        for k in REQUIRED_SYMBOL_KEYS
            haskey(s, k) || error("Symbol entry missing required key: $(k)")
        end
        sid = String(s["id"])
        push!(ids, sid)
        cat = String(s["category"])
        cat in cat_set || error("Symbol $(sid) references unknown category $(cat)")
    end

    length(unique(ids)) == length(ids) || error("Duplicate symbol ids in symbols.yaml")
    return nothing
end

function _symbols_by_category(spec)
    symbols = spec["symbols"]
    grouped = Dict{String,Vector{Any}}()
    for s in symbols
        cat = String(s["category"])
        if !haskey(grouped, cat)
            grouped[cat] = Any[]
        end
        push!(grouped[cat], s)
    end
    for (_, group) in grouped
        sort!(group; by=x -> String(x["id"]))
    end
    return grouped
end

function _render_tex(spec; generated_path::String)
    grouped = _symbols_by_category(spec)
    categories = spec["categories"]

    lines = String[]
    push!(lines, "% Auto-generated by scripts/generate_symbols.jl. Do not edit by hand.")
    push!(lines, "% Source: $(generated_path)")
    push!(lines, "\\section*{List of Symbols}")
    push!(lines, "\\small")
    push!(lines, "\\setlength{\\tabcolsep}{5pt}")
    push!(lines, "\\renewcommand{\\arraystretch}{1.15}")
    push!(lines, "\\begin{center}")
    push!(lines, "\\begin{tabular}{p{0.14\\textwidth}p{0.34\\textwidth}p{0.18\\textwidth}p{0.24\\textwidth}}")
    push!(lines, "\\toprule")
    push!(lines, "\\textbf{Symbol} & \\textbf{Meaning} & \\textbf{Units} & \\textbf{Code Mapping} \\\\")
    push!(lines, "\\midrule")

    first_cat = true
    for cat in categories
        cat_id = String(cat["id"])
        cat_name = _latex_escape(String(cat["name"]))
        entries = get(grouped, cat_id, Any[])
        isempty(entries) && continue

        if !first_cat
            push!(lines, "\\addlinespace[0.6em]")
        end
        first_cat = false

        push!(lines, "\\multicolumn{4}{l}{\\textbf{$(cat_name)}} \\\\")
        push!(lines, "\\midrule")
        for e in entries
            symbol_tex = String(e["symbol_tex"])
            meaning = _latex_escape(String(e["name"]))
            units_tex = String(e["units_tex"]) == "-" ? "---" : "\\($(String(e["units_tex"]))\\)"
            code_key = _latex_escape(String(e["code_key"]))
            push!(lines, "\\($(symbol_tex)\\) & $(meaning) & $(units_tex) & \\texttt{$(code_key)} \\\\")
        end
    end

    push!(lines, "\\bottomrule")
    push!(lines, "\\end{tabular}")
    push!(lines, "\\end{center}")
    push!(lines, "\\normalsize")
    push!(lines, "")
    return join(lines, "\n")
end

function _render_markdown(spec; generated_path::String)
    grouped = _symbols_by_category(spec)
    categories = spec["categories"]

    lines = String[]
    push!(lines, "# Symbols Reference")
    push!(lines, "")
    push!(lines, "Auto-generated from `$(generated_path)`. Do not edit by hand.")
    push!(lines, "")

    for cat in categories
        cat_id = String(cat["id"])
        entries = get(grouped, cat_id, Any[])
        isempty(entries) && continue
        push!(lines, "## $(String(cat["name"]))")
        push!(lines, "")
        push!(lines, "| Symbol | Meaning | Units | Code Mapping |")
        push!(lines, "| --- | --- | --- | --- |")
        for e in entries
            symbol_md = String(e["symbol_md"])
            meaning = String(e["name"])
            units_md = String(e["units_md"])
            code_key = String(e["code_key"])
            push!(lines, "| `$(symbol_md)` | $(meaning) | $(units_md) | `$(code_key)` |")
        end
        push!(lines, "")
    end

    return join(lines, "\n")
end

function _build_context(spec)
    context = Dict{String,String}()
    for e_any in spec["symbols"]
        e = e_any
        id = String(e["id"])
        context["symbol_$(id)_tex"] = String(e["symbol_tex"])
        context["symbol_$(id)_md"] = String(e["symbol_md"])
        context["symbol_$(id)_code"] = String(e["code_key"])
        context["symbol_$(id)_name"] = String(e["name"])
        context["symbol_$(id)_units_tex"] = String(e["units_tex"])
    end
    return context
end

function generate_symbols_assets(; spec_path::String="spec/symbols.yaml",
    tex_out::String="reports/generated/sections/list_of_symbols.tex",
    md_out::String="docs/SYMBOLS.md")
    spec = _read_yaml(spec_path)
    _validate_spec(spec)

    mkpath(dirname(tex_out))
    mkpath(dirname(md_out))

    tex = _render_tex(spec; generated_path=spec_path)
    md = _render_markdown(spec; generated_path=spec_path)

    write(tex_out, tex)
    write(md_out, md)

    context = _build_context(spec)
    return context, tex_out, md_out
end

end # module SymbolSSOT

if abspath(PROGRAM_FILE) == @__FILE__
    context, tex_out, md_out = SymbolSSOT.generate_symbols_assets()
    println("Generated symbols artifacts:")
    println("  TeX: $(tex_out)")
    println("  MD:  $(md_out)")
    println("Loaded symbol context keys: $(length(context))")
end